# syntax=docker/dockerfile:experimental
FROM node:11.10.0-slim as BUILD

WORKDIR /app/

COPY . /app/
RUN yarn install
RUN yarn tsc
RUN cp package.json dist/package.json
WORKDIR /app/dist/
RUN yarn install --prod

FROM node:11.10.0-slim as PROD
WORKDIR /app
COPY --from=build /app/dist/ /app

EXPOSE 3000

CMD ["node", "index.js"] 